"""switched birthday info loc

Revision ID: 01990c39796e
Revises: ffb64da907d6
Create Date: 2024-02-09 18:52:41.663132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01990c39796e'
down_revision = 'ffb64da907d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'birthday', ['birthday_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_birthday_id_fkey', type_='foreignkey')
        batch_op.drop_column('birthday_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_birthday_id_fkey', 'birthday', ['birthday_id'], ['id'])

    with op.batch_alter_table('personal_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('birthday_id')

    # ### end Alembic commands ###
