"""empty message

Revision ID: 5b07a10c62d4
Revises: e4145b727683
Create Date: 2023-07-08 16:49:20.349212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b07a10c62d4'
down_revision = 'e4145b727683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_address_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_email_address_key', ['email_address'])

    # ### end Alembic commands ###
