"""empty message

Revision ID: 94686c87a3f0
Revises: 5b07a10c62d4
Create Date: 2023-07-08 16:50:02.163877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94686c87a3f0'
down_revision = '5b07a10c62d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
