"""empty message

Revision ID: e7e773e73fbb
Revises: 94686c87a3f0
Create Date: 2023-07-10 18:06:07.867458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e773e73fbb'
down_revision = '94686c87a3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'birthday', ['birthday_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('birthday_id')

    # ### end Alembic commands ###
